version = 1

exclude_patterns = [
  "/public/js/app.js",
  "/public/index.php",
  "/index.php",
  "/server.php",
  "/artisan"
]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "php"
enabled = true

[[transformers]]
name = "php-cs-fixer"
enabled = true

[[transformers]]
name = "prettier"
enabled = true

[[transformers]]
name = "standardjs"
enabled = true
