version = 1

exclude_patterns = [
  "/public/js/app.js",
  "/public/index.php",
  "/index.php",
  "/server.php",
  "/artisan"
]

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "php"

[[transformers]]
name = "php-cs-fixer"

[[transformers]]
name = "prettier"

[[transformers]]
name = "standardjs"